<h1>1. Matrix product is calculated manually </h1>

| Position | Calculation                                          | Result |
|----------|------------------------------------------------------|--------|
| 1, 1     | \(-1 * 0) + (2 * 0) + (3 * 2)                        | 6      |
| 1, 2     | \(-1 * 2) + (2 * 2) + (3 * 9)                        | 29     |
| 1, 3     | \(-1 * 1) + (2 * -8) + (3 * -1)                      | -20    |
| 2, 1     | \(4 * 0) + (-5 * 0) + (6 * 2)                        | 12     |
| 2, 2     | \(4 * 2) + (-5 * 2) + (6 * 9)                        | 52     |
| 2, 3     | \(4 * 1) + (-5 * -8) + (6 * -1)                      | 38     |
| 3, 1     | \(7 * 0) + (8 * 0) + (-9 * 2)                        | -18    |
| 3, 2     | \(7 * 2) + (8 * 2) + (-9 * 9)                        | -51    |
| 3, 3     | \(7 * 1) + (8 * -8) + (-9 * -1)                      | -48    |


# Explanation

## Thought Process

1. **Input Matrices**: We start with two input matrices, `A` and `B`, where `A` has dimensions `m x n` and `B` has dimensions `n x p`.

2. **Checking Compatibility**: Before multiplying the matrices, we need to ensure that the number of columns in `A` matches the number of rows in `B`. If not, the matrices cannot be multiplied.

3. **Result Matrix Initialization**: We initialize an empty result matrix `C` with dimensions `m x p`, where each element is initially set to zero. The resulting matrix would be `C` `m x p` if `A` `m x n` and `B` `n x p` where `A` (`n`) = `B` (`n`)

4. **Multiplying Matrices**: To compute each element `C[i][j]` of the result matrix `C`, we perform the dot product of the `i-th` row of matrix `A` and the `j-th` column of matrix `B`.

5. **Iterating over Elements**: We iterate over each element `C[i][j]` and compute its value by summing the products of corresponding elements from the `i-th` row of `A` and `j-th` column of `B`.

6. **Return Result Matrix**: Once all elements of the result matrix `C` are computed, we return the final result.

## Example

Consider matrices:

A = [\[3, 1, 4\]]

B = [[4, 3], [2, 5], [6, 8]]

After multiplication, the resulting matrix C will be:

C = [[32, 44]]


<h1> 2. Calculation by NumPy function</h1>

In [29]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result = np.matmul(a, b)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h1>3.Implementation of calculation of a certain element </h1>

In [30]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result = 0
for k in range(len(a_ndarray[0])):
        result += a_ndarray[0][k] * b_ndarray[k][0]

print("Result:", result)

Result: 6


<h1>4. Creating a function that performs matrix multiplication </h1>

In [31]:

def multiply_matrices(a, b):
    a_cols = len(a[0])
    a_rows = len(a)
    b_cols = len(b[0])
    b_rows = len(b)
    result = np.zeros((a_rows, b_cols), dtype=int)
    if a_cols != b_rows:
        return "Cannot multiply matrices"
    for i in range(a_rows):
        print(f"Row {i+1} will be multiplied ", b_cols, " times")
        for j in range(b_cols):
            for k in range(b_rows):
                result[i][j] += a[i][k] * b[k][j]
    return result    
      
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])        
print(multiply_matrices(d_ndarray, e_ndarray))
print(multiply_matrices(a_ndarray, b_ndarray))


Cannot multiply matrices
Row 1 will be multiplied  3  times
Row 2 will be multiplied  3  times
Row 3 will be multiplied  3  times
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h1>5. Judge the input whose calculation is not defined <h1>

In [32]:
# Already implement the function with guard clauses

<h1>6. Transposition </h1>

In [33]:
print("Transposed product of the matrices\n", np.transpose(multiply_matrices(a_ndarray, b_ndarray)))

Row 1 will be multiplied  3  times
Row 2 will be multiplied  3  times
Row 3 will be multiplied  3  times
Transposed product of the matrices
 [[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]
